---
# Source: ssp-infra/charts/fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssp-infra-fluent-bit
  namespace: ssp
  labels:
    helm.sh/chart: fluent-bit-0.20.3
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: ssp-infra
    app.kubernetes.io/version: "1.9.5"
    app.kubernetes.io/managed-by: Helm
