---
# Source: ssp-infra/templates/db-metrics-exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ssp-ssp-db-metrics-exporter
  namespace: ssp
  labels:
    app: ssp-infra-db-metrics-exporter
    chart: ssp-infra-1.0.3228
    heritage: Helm
    release: ssp-infra
    ssp-infra-prometheus-metrics: db-metrics
spec:
  type: ClusterIP
  ports:
    - name: db-metrics
      port: 9104
      targetPort: db-metrics
  selector:
    app: ssp-infra-db-metrics-exporter
    release: ssp-infra
