---
# Source: ssp-infra/templates/db-create-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ssp-infra-ssp-infra-create-db-job-6ugw
  namespace: ssp
  labels:
    app: ssp-infra
    app.kubernetes.io/name: ssp-infra-create-db-job
    app.kubernetes.io/version: "1.0.3228"
    app.kubernetes.io/component: utility
    app.kubernetes.io/part-of: ssp-infra
    app.kubernetes.io/instance: ssp-infra
    app.kubernetes.io/managed-by: Helm 
    helm.sh/chart: ssp-infra-1.0.3228
  
spec:
  # currently we do not want to restart in case the job fails
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: ssp-infra
        app.kubernetes.io/name: ssp-infra-create-db-job
        app.kubernetes.io/version: "1.0.3228"
        app.kubernetes.io/component: utility
        app.kubernetes.io/part-of: ssp-infra
        app.kubernetes.io/instance: ssp-infra
        app.kubernetes.io/managed-by: Helm 
        helm.sh/chart: ssp-infra-1.0.3228
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: ssp-staging-registrypullsecret
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 1337
      containers:
      - name: ssp-db-create
        image: "percona/percona-xtradb-cluster:8.0.23-14.1"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: ssp-ssp-db-pxc
                key: root
          - name: MYSQL_HOST
            value: ssp-ssp-db-pxc
          - name: MYSQL_TCP_PORT
            value: "3306"
          - name: SCHEMA_NAME
            value: iamauth
          - name: SCHEMA_USER
            value: iamauth
          - name: SCHEMA_PWD
            valueFrom:
              secretKeyRef:
                name: ssp-ssp-db-pxc
                key: mysql-password
        command: ["bash"]
        args: ["-c", "until ( mysql -h${MYSQL_HOST} -P${MYSQL_TCP_PORT} -u${MYSQL_USER} -p${MYSQL_PWD} -e \"CREATE DATABASE IF NOT EXISTS ${SCHEMA_NAME};  CREATE USER IF NOT EXISTS ${SCHEMA_USER} IDENTIFIED WITH mysql_native_password BY '${SCHEMA_PWD}'; ALTER USER ${SCHEMA_USER} IDENTIFIED WITH mysql_native_password BY '${SCHEMA_PWD}'; GRANT ALL ON ${SCHEMA_NAME}.* TO ${SCHEMA_USER} ;\" );  do echo waiting for mysql on ${MYSQL_HOST}:${MYSQL_TCP_PORT}; sleep 5; done;"]
