---
# Source: ssp-infra/templates/db-metrics-exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-ssp-db-metrics-exporter
  namespace: ssp
  labels:
    app: ssp-infra-db-metrics-exporter
    chart: ssp-infra-1.0.3228
    heritage: Helm
    release: ssp-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp-infra-db-metrics-exporter
      release: ssp-infra
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ssp-infra-db-metrics-exporter
        # note: chart version specifically removed from "chart" given the mysqld_exporter image as specified in values.yaml is external
        chart: ssp-infra
        heritage: Helm
        release: ssp-infra
    spec:
      imagePullSecrets:
      - name: ssp-staging-registrypullsecret
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 1337
      containers:
        - name: ssp-infra-db-metrics-exporter
          image: "prom/mysqld-exporter:v0.12.1"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
          - name: MYSQL_HOST
            value: ssp-ssp-db-pxc
          - name: MYSQL_MONITOR_USER
            value: monitor
          - name: MYSQL_MONITOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ssp-ssp-db-pxc
                key: monitor
          command:
          - 'sh'
          - '-c'
          - 'DATA_SOURCE_NAME="${MYSQL_MONITOR_USER}:${MYSQL_MONITOR_PASSWORD}@(${MYSQL_HOST}:3306)/" /bin/mysqld_exporter --collect.perf_schema.eventsstatements'
          ports:
          - name: db-metrics
            containerPort: 9104
          livenessProbe:
            httpGet:
              path: /
              port: db-metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: db-metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 300Mi
