---
# Source: ssp-infra/charts/fluent-bit/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "ssp-infra-fluent-bit-test-connection"
  namespace: ssp
    helm.sh/chart: fluent-bit-0.20.3
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: ssp-infra
    app.kubernetes.io/version: "1.9.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: "busybox:latest"
      imagePullPolicy: Always
      command: ['wget']
      args: ['ssp-infra-fluent-bit:2020']
  imagePullSecrets:
    - name: ssp-staging-registrypullsecret
  restartPolicy: Never
