apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-ing-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: ssp-ing
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: ssp-infra
      repoURL: https://ssp-helm-charts-staging.storage.googleapis.com
      targetRevision: 4.0.0-1144.stage
      helm:
        valueFiles: 
        - $values/envs/idsp-ing/values/ssp-ing-infra-values.yaml
#    - repoURL: https://github.com/iyesdendeni/idsp-with-argocd.git
#      targetRevision: main
#      path: envs/idsp-ing/manifests
    - repoURL: https://github.com/iyesdendeni/idsp-with-argocd.git
      targetRevision: main
      ref: values
  syncPolicy:
    manual:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true