{{- if index .Values "fluent-bit" "enabled" -}}
{{- $foundDepricatedCM := ( include "exists.deprecated.fluentbit.configmap" . ) }}
#create the new config map only if there is no old (deprecated) fluent-bit configmap
#(determined by checking the cmversion annotation, $foundDepricatedCM = {{$foundDepricatedCM}})
{{ if eq $foundDepricatedCM "false" }}

{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index .Values "fluent-bit" "existingConfigMap" }}
  labels:
    app: {{ template "ssp-infra.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    configVersion: "1.0"
data:
  fluent-bit-service.conf: |
    [SERVICE]
        Flush        {{ .Values.sspfbService.flush }}
        Daemon       Off
        Log_Level    {{ .Values.sspfbService.logLevel }}
        Parsers_File conf/parsers.conf
        Streams_File conf/fluent-bit-streamer.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    {{ index .Values "fluent-bit"  "service" "port" }}
        Health_Check On

  fluent-bit-input.conf: |
{{- $sspLogFilter := print (required "***** A valid sspReleaseName value required in values.yaml or passed in via --set sspReleaseName=<value>!  If this is an upgrade, specify --reuse-values. *****" .Values.sspReleaseName) "-ssp-*.log" }}
{{- $sspInput := dict "logFileFilter" $sspLogFilter
                      "tagWith"       "ssp_msg"
                      "dbPath"        (print ($root.Values.sspReleaseName) "-ssp") }}
{{- $inputsList := list $sspInput }}

{{- $ssphzInput := dict    "logFileFilter"        "ssp-hazelcast-entp-*.log"
                           "tagWith"              "ssp_msg"
                           "parser"               "hzcri"
                           "dbPath"               (print ($root.Values.sspReleaseName) "-ssphz")
                           "skipKubernetesFilter" true }}
{{- $nginxInput := dict    "logFileFilter"        "ingress-nginx-controller-*.log"
                           "tagWith"              "ssp_msg"
                           "skipKubernetesFilter" true }}

{{- $ssopsInput := dict    "logFileFilter" "*-policy-server-*_*_*.log"
                           "tagWith"       "sso_ps_log_msg" }}
{{- $ssoadminInput := dict "logFileFilter" "*-admin-*_*_*.log"
                           "tagWith"       "sso_admin_log_msg" }}
{{- $ssoagInput := dict    "logFileFilter" "*-access-gateway-*_*_*.log"
                           "tagWith"       "sso_ag_log_msg" }}

{{- $inputsList = append $inputsList (deepCopy $ssphzInput) }}
{{- if .Values.sspfbService.ingressLogsIncluded }}
{{- $inputsList = append $inputsList (deepCopy $nginxInput) }}
{{- end }}
{{- if .Values.global.sso.enabled }}
{{- $inputsList = append $inputsList (deepCopy $ssopsInput) }}
{{- $inputsList = append $inputsList (deepCopy $ssoadminInput) }}
{{- $inputsList = append $inputsList (deepCopy $ssoagInput) }}
{{- end }}

{{- $inputsList = concat ($inputsList) (index .Values "fluent-bit" "customConfig" "additionalInputs")  }}
{{- range $currentInput := $inputsList }}
    [INPUT]
        Name              tail
        Path              /var/log/containers/{{tpl $currentInput.logFileFilter $root}}
        {{- if $currentInput.parser }}
        Parser            {{tpl $currentInput.parser $root}}
        {{- else }}
        Parser            {{$root.Values.sspfbService.parser}}
        {{- end }}
        Tag               {{tpl $currentInput.tagWith $root}}.*
        Refresh_Interval  {{ $root.Values.input.tail.refreshInterval |default "5" }}
        Mem_Buf_Limit     {{ $root.Values.input.tail.memBufLimit }}
        Buffer_Max_Size   {{ $root.Values.input.tail.bufMaxSize |default "1M" }}
        Buffer_Chunk_Size {{ $root.Values.input.tail.bufChunkSize |default "128k" }}
        Skip_Long_Lines   {{ $root.Values.input.tail.skipLongLines |default "On" }}

{{- if $root.Values.input.tail.ignore_older }}
        Ignore_Older      {{ $root.Values.input.tail.ignore_older }}
{{- end }}
{{- if $root.Values.input.tail.preserveLastProcessedLine.enabled }}
{{- if $currentInput.dbPath }}
        DB                /var/log/tail-containers-state-{{tpl $currentInput.dbPath $root}}.db
{{- else }}
        DB                /var/log/tail-containers-state-{{tpl $currentInput.tagWith $root}}.db
{{- end }}
        DB.Sync           {{ $root.Values.input.tail.dbSyncMode |default "Normal" }}
{{- end }}
{{- if $root.Values.input.tail.additionalInputParams }}
{{ $root.Values.input.tail.additionalInputParams | indent 8 }}
{{- end }}
{{- end }}


  fluent-bit-filter.conf: |
{{- range $currentInput := $inputsList }}
{{- if not $currentInput.skipKubernetesFilter }}
    [FILTER]
        Name                kubernetes
        Match               {{tpl $currentInput.tagWith  $root}}.*
        Kube_Tag_Prefix     {{tpl $currentInput.tagWith  $root}}.var.log.containers.
        Kube_URL            {{ $root.Values.filter.kubeURL }}
        Kube_CA_File        {{ $root.Values.filter.kubeCAFile }}
        Kube_Token_File     {{ $root.Values.filter.kubeTokenFile }}
        Merge_Log           On
        Keep_Log            Off
        #Merge_Log_Key       ""
        K8S-Logging.Parser  Off
        #K8S-Logging.Exclude On
        #Use_Journal         On
{{ end }}
{{ end }}

{{- range $currentFilter := (index .Values "fluent-bit" "customConfig" "additionalFilters") }}
  {{- range $currentTag := $currentFilter.tags }}
    [FILTER]
        Match {{ $currentTag }}
    {{- (tpl $currentFilter.template $root)|replace "${tag}" $currentTag|trim |nindent 8}}
  {{ end }}
{{ end }}


  fluent-bit-output.conf: |
{{- range $currentOutput := index .Values "fluent-bit" "customConfig" "outputs" }}
  {{- range $currentTag := $currentOutput.tags }}
    [OUTPUT]
        Match {{ $currentTag }}
    {{- (tpl $currentOutput.template $root)|replace "${tag}" $currentTag|trim |nindent 8}}
  {{ end }}
{{ end }}


  fluent-bit-streamer.conf: |
    [STREAM_TASK]
        Name   ssp_log
        Exec   CREATE STREAM ssp_log WITH (tag='ssp_log') AS SELECT * from TAG:'ssp_msg.*' WHERE type = 'log';
    [STREAM_TASK]
        Name   ssp_audit
        Exec   CREATE STREAM ssp_audit WITH (tag='ssp_audit') AS SELECT * from TAG:'ssp_msg.*' WHERE type = 'audit';
    [STREAM_TASK]
        Name   ssp_tp_log
        Exec   CREATE STREAM ssp_tp_log WITH (tag='ssp_tp_log') AS SELECT * from TAG:'ssp_msg.*' WHERE NOT @record.contains(type);
{{- $ssoTagsList := list
                    (dict "current" "sso_ps_log_msg" "new" "sso_ps_log")
                    (dict "current" "sso_admin_log_msg" "new" "sso_admin_log")
                    (dict "current" "sso_ag_log_msg" "new" "sso_ag_log") }}
{{- $ssoStreamTask := dict "tags" $ssoTagsList
                           "template" "Exec CREATE STREAM ${newTag} WITH (tag='${newTag}') AS SELECT * from TAG:'${currentTag}.*';" }}
{{- $additionalStreamTasks := index .Values "fluent-bit" "customConfig" "additionalStreamTasks"}}


{{- if .Values.global.sso.enabled }}
  {{- $additionalStreamTasks = append $additionalStreamTasks (deepCopy $ssoStreamTask) }}
{{- end }}

{{- range $currentTask := $additionalStreamTasks }}
  {{- range $taskTags := $currentTask.tags }}
    [STREAM_TASK]
        Name   {{$taskTags.new}}
    {{-  (tpl $currentTask.template $root )|replace "${newTag}" $taskTags.new |replace "${currentTag}" $taskTags.current|trim |nindent 8 }}
  {{- end }}
{{ end }}

  fluent-bit.conf: |
    @INCLUDE conf/fluent-bit-service.conf
    @INCLUDE conf/fluent-bit-input.conf
    @INCLUDE conf/fluent-bit-filter.conf
    @INCLUDE conf/fluent-bit-output.conf

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Keep   off
        Time_Key    time
        # TBD: update to use log entry's timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Decode_Field_As escaped log
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name        hzcri
        Format      regex
        Regex       ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%d T%H:%M:%S.%L%z
  {{- if (index .Values "fluent-bit" "customConfig" "additionalParsers") }}
{{ (index .Values "fluent-bit" "customConfig" "additionalParsers") | indent 4 }}
  {{- end }}

{{- end -}}
{{- end -}}
