{{- if and .Values.db.enabled (not .Values.db.existingSecret) -}}
{{- if .Release.IsInstall -}}
{{- $dbsecretname := ( include "db.secretName.def" . ) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $dbsecretname ) -}}
{{- $internaldbsecretname := printf "internal-%s" ( include "db.pxcName.def" . ) -}}
{{- $internalsecret := (lookup "v1" "Secret" .Release.Namespace $internaldbsecretname ) -}}
{{- if or $secret $internalsecret -}}
{{- $dbpvcname := printf "datadir-%s-pxc-<N>" ( include "db.pxcName.def" . ) -}} 
{{- $errmsg := printf "***** Have you intended to completely uninstall the DB? DB operator secret(s) detected indicating presence of internal DB. Unable to proceed until Secrets %s and %s, and related PVCs %s have been deleted. If you intended to redeploy this chart with the persistence of the previous DB service, then deploy this chart with --set db.existingSecret=\"%s\" parameter *****" $dbsecretname $internaldbsecretname $dbpvcname $dbsecretname -}}
{{- required $errmsg .Values.randomValueThatDoesNotExist }}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db.secretName.def" . }}
  annotations:
    # specifically keeping this secret to ensure DB passwords are not accidentally deleted if secret was generated with random values
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  mysql-password: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "schema" "valuekey" "password" "secretkey" "mysql-password" }}
  root: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "root" "secretkey" "root" }}
  xtrabackup: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "xtrabackup" "secretkey" "xtrabackup" }}
  monitor: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "monitor" "secretkey" "monitor" }}
  clustercheck: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "clustercheck" "secretkey" "clustercheck" }}
  proxyadmin: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "proxyadmin" "secretkey" "proxyadmin" }}
  pmmserver: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "pmmserver" "secretkey" "pmmserver" }}
  operator: {{ template "db.secretName.password" dict "root" . "valuesparentkey" "password" "valuekey" "operator" "secretkey" "operator" }}
{{- end -}}