#USER-SUPPLIED VALUES: null
db:
  enabled: true
fluent-bit:
  enabled: true
  imagePullSecrets:
  - name: ssp-staging-registrypullsecret
global:
  registry:
    existingSecrets:
    - name: ssp-infra-registrypullsecret
sspReleaseName: ssp
