#USER-SUPPLIED VALUES: null
hazelcast-enterprise:
  cluster:
    memberCount: 2
  image:
    pullSecrets:
    - ssp-staging-registrypullsecret
ssp:
  deployment:
    size: demo
  featureFlags:
    dataseed:
      enabled: true
    mcpserver:
      enabled: true
    multiidstore:
      enabled: true
  global:
    drSite: false
    ssp:
      registry:
        existingSecrets:
        - name: ssp-staging-registrypullsecret
  db:
    serviceHost: ssp-ssp-db-pxc
    servicePort: 3306
  ingress:
    host: ssp.id-broadcom.com
    tls:
      secretName: ssp-general-tls
    type: gatewayapi
    gatewayApi:
    gatewayApiConfig:
      gatewayClassName: gke-l7-global-external-managed 
      createGateway: true
      createBackendTLSPolicy: false
