apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ssp
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: ssp-infra
      repoURL: https://ssp-helm-charts-staging.storage.googleapis.com/ssp-maint-patch
      targetRevision: 4.0.2-1031.stage
      helm:
        valueFiles: 
        - $values/envs/idsp-main/values/ssp-infra-values.yaml
    - repoURL: https://github.com/iyesdendeni/idsp-with-argocd.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true