apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-gw
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
# SSP maint: chart repo "ssp-helm-charts-maint" → ssp-maint-patch; images → us.gcr.io/saasdev-sed-ssp-hp/maint/
# See docs/ssp-maint-reference.md
spec:
  destination:
    namespace: ssp-gw
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: ssp
      repoURL: https://ssp-helm-charts-staging.storage.googleapis.com/ssp-maint-patch
      targetRevision: 4.0.2-1031.stage
#      repoURL: https://ssp-helm-charts-staging.storage.googleapis.com
#      targetRevision: 4.0.0-1144.stage
      helm:
        valueFiles: 
        - $values/envs/idsp-gw/values/ssp-gw-values.yaml
    - repoURL: https://github.com/iyesdendeni/idsp-with-argocd.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true