
global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/mysql
  tag: 8.4.5-debian-12-r0

architecture: replication

auth:
  rootPassword: P@ssword01
  database: iamauth
  username: iamauth
  password: P@ssword01

primary:
  persistence:
    enabled: true
    storageClass: premium-rwo
    size: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
  configuration: |
    [mysqld]
    innodb_buffer_pool_size=1G
    max_connections=200
    character-set-server=utf8mb4

# Enable read replicas
secondary:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: premium-rwo
    size: 50Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi

metrics:
  enabled: false
  serviceMonitor:
    enabled: false